package com.practice;

class Brackets{	
	synchronized public static void generateBrackets(String threadCode) {		//Static method for synchronization
		for(int i=1;i<=10;i++) {
			if(i<=5)
			{
				System.out.print("[");
			}else {
				System.out.print("]");
			}
		}
		System.out.println("Generated by thread:"+threadCode);
	}
}
public class Main {

	
	public static void main(String[] args) {
		new Thread(new Runnable() {
			
			@Override
			public void run() {
				
				for(int i=0;i<5;i++)
				{
					Brackets.generateBrackets("Thread1");				//call a method without an object and defined method as static to prevent inconsistency
				}
			}
		}).start();
		
		new Thread(new Runnable() {
			
			@Override
			public void run() {
				
				for(int i=0;i<5;i++)
				{
					Brackets.generateBrackets("Thread2");
				}
			}
		}).start();


	}

}
